/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author manum
 */
public class AdminVista extends javax.swing.JFrame {

    /**
     * Creates new form AdminVista
     */
    public AdminVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnServicios = new javax.swing.JButton();
        BtnRepuestos = new javax.swing.JButton();
        BtnClietnes = new javax.swing.JButton();
        BtnProgreso = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnServicios.setBackground(new java.awt.Color(204, 204, 204));
        BtnServicios.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        BtnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Servicios.png"))); // NOI18N
        BtnServicios.setText("Servicios");
        jPanel1.add(BtnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 30));

        BtnRepuestos.setBackground(new java.awt.Color(204, 204, 204));
        BtnRepuestos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        BtnRepuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Repuestos.png"))); // NOI18N
        BtnRepuestos.setText("Repuestos");
        jPanel1.add(BtnRepuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        BtnClietnes.setBackground(new java.awt.Color(204, 204, 204));
        BtnClietnes.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        BtnClietnes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Clientes.png"))); // NOI18N
        BtnClietnes.setText("<html><center>Clientes y Autmoviles </center></html>\n");
        BtnClietnes.setActionCommand("Clientes");
        jPanel1.add(BtnClietnes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 50));

        BtnProgreso.setBackground(new java.awt.Color(204, 204, 204));
        BtnProgreso.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        BtnProgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Progreso.png"))); // NOI18N
        BtnProgreso.setText("<html><center> Progreso de Automoviles</center></html> ");
        BtnProgreso.setActionCommand("Progreso");
        jPanel1.add(BtnProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 150, 50));

        btnReportes.setBackground(new java.awt.Color(204, 204, 204));
        btnReportes.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Reportes.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 130, 40));

        BtnCerrar.setBackground(new java.awt.Color(51, 102, 255));
        BtnCerrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Cerrar.png"))); // NOI18N
        BtnCerrar.setText("Cerrar");
        jPanel1.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCerrar;
    public javax.swing.JButton BtnClietnes;
    public javax.swing.JButton BtnProgreso;
    public javax.swing.JButton BtnRepuestos;
    public javax.swing.JButton BtnServicios;
    public javax.swing.JButton btnReportes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
