/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.HiloTablas;
import Controller.ActualizarTablasListener;
import Model.Vehiculos;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manum
 */
public class ProgresoAdminVista extends javax.swing.JFrame implements ActualizarTablasListener  {

    
    
    /**
     * Creates new form ProgresoAdminVista
     */
    public ProgresoAdminVista() {
        initComponents();
        HiloTablas.setListenerTablas(this); // Conectar vista al hilo
    }
    
    @Override
    public void actualizarTablaEspera(Vehiculos[] colaEspera) {
        SwingUtilities.invokeLater(() -> {
            DefaultTableModel tablaNueva = (DefaultTableModel) TablaEspera.getModel();
            tablaNueva.setRowCount(0); // Limpiar la tabla

            for (int i = 0; i < colaEspera.length; i++) {
                Vehiculos v = colaEspera[i];
                if (v != null) {
                    tablaNueva.addRow(new Object[]{
                        (i + 1), // Número de orden
                        v.getMarca() + " " + v.getModelo(), // Vehículo
                        v.getDueño() // Cliente
                    });
                }
            }
        });
    }
    
    @Override
    public void actualizarTablaServicio(Vehiculos[] colaServicio) {
        SwingUtilities.invokeLater(() -> {
            DefaultTableModel tablaNueva = (DefaultTableModel) TablaServicio.getModel();
            tablaNueva.setRowCount(0); // Limpiar la tabla

            for (int i = 0; i < colaServicio.length; i++) {
                Vehiculos v = colaServicio[i];
                if (v != null){
                    tablaNueva.addRow(new Object[]{
                        (i + 1), // Número de orden
                        v.getMarca() + " " + v.getModelo(), // Vehículo
                        v.getDueño(), // Cliente
                        "No asignado" // Mecánico
                    });
                    tablaNueva.setValueAt("pepe", 0,3);
                }
            }
        });
    }
    
    @Override
    public void actualizarTablaListos(Vehiculos[] colaListos) {
        SwingUtilities.invokeLater(() -> {
            DefaultTableModel tablaNueva = (DefaultTableModel) TablaListo.getModel();
            tablaNueva.setRowCount(0); // Limpiar la tabla

            for (int i = 0; i < colaListos.length; i++) {
                Vehiculos v = colaListos[i];
                if (v != null) {
                    tablaNueva.addRow(new Object[]{
                        (i + 1), // Número de orden
                        v.getMarca() + " " + v.getModelo(), // Vehículo
                        v.getDueño(), // Cliente
                        v.getSercicio().getNombre_servicio(), // Nombre del servicio
                        v.getCostoTotal() // Precio total
                    });
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEspera = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaServicio = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaListo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaEspera.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        TablaEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Vehiculo", "Cliente"
            }
        ));
        TablaEspera.setGridColor(new java.awt.Color(0, 0, 0));
        TablaEspera.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(TablaEspera);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 250, 150));

        TablaServicio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        TablaServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Vehiculo", "Cliente", "Mecanico"
            }
        ));
        TablaServicio.setGridColor(new java.awt.Color(0, 0, 0));
        TablaServicio.setInheritsPopupMenu(true);
        jScrollPane2.setViewportView(TablaServicio);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 250, 150));

        TablaListo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        TablaListo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Vehiculo", "Cliente", "Servicio", "Total"
            }
        ));
        TablaListo.setGridColor(new java.awt.Color(0, 0, 0));
        TablaListo.setInheritsPopupMenu(true);
        jScrollPane3.setViewportView(TablaListo);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 370, 200));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carros listos para entregar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cola de espera");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Carros en atencion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgresoAdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgresoAdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgresoAdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgresoAdminVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgresoAdminVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaEspera;
    public javax.swing.JTable TablaListo;
    public javax.swing.JTable TablaServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
