/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author manum
 */
public class RegistroVista extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVista
     */
    public RegistroVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnAñadir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        txtImg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtPlaca.setBackground(new java.awt.Color(0, 0, 0));
        txtPlaca.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(204, 204, 204));
        txtPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlaca.setText("000AAA");
        txtPlaca.setBorder(null);
        txtPlaca.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtPlaca.setEnabled(false);
        txtPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPlacaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPlacaMouseExited(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlacaKeyPressed(evt);
            }
        });
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Placa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtModelo.setBackground(new java.awt.Color(0, 0, 0));
        txtModelo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(204, 204, 204));
        txtModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModelo.setText("Ingrese el modelo");
        txtModelo.setBorder(null);
        txtModelo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtModelo.setEnabled(false);
        txtModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtModeloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtModeloMouseExited(evt);
            }
        });
        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModeloKeyPressed(evt);
            }
        });
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtMarca.setBackground(new java.awt.Color(0, 0, 0));
        txtMarca.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(204, 204, 204));
        txtMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMarca.setText("Ingrese la marca");
        txtMarca.setBorder(null);
        txtMarca.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtMarca.setEnabled(false);
        txtMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMarcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMarcaMouseExited(evt);
            }
        });
        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMarcaKeyPressed(evt);
            }
        });
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 50, 110, 10));

        btnAñadir.setBackground(new java.awt.Color(51, 51, 255));
        btnAñadir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir a tu Lista");
        btnAñadir.setActionCommand("Añadir");
        btnAñadir.setBorder(null);
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, 40));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, 10));

        txtImg.setBackground(new java.awt.Color(0, 0, 0));
        txtImg.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtImg.setForeground(new java.awt.Color(204, 204, 204));
        txtImg.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtImg.setText("XXXX");
        txtImg.setBorder(null);
        txtImg.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtImg.setEnabled(false);
        txtImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtImgMouseExited(evt);
            }
        });
        txtImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImgActionPerformed(evt);
            }
        });
        txtImg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtImgKeyPressed(evt);
            }
        });
        jPanel1.add(txtImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Imangen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(51, 153, 0));
        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyPressed
        if (txtPlaca.getText().equals("000AAA")) {
            txtPlaca.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaKeyPressed

    private void txtPlacaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlacaMouseEntered
        txtPlaca.setEnabled(true);
        txtPlaca.requestFocus();
        txtPlaca.setCaretPosition(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaMouseEntered

    private void txtPlacaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlacaMouseExited
        if (txtPlaca.getText().equals("")) {
            txtPlaca.setText("000AAA");
            txtPlaca.setEnabled(false);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaMouseExited

    private void txtMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyPressed
        if (txtMarca.getText().equals("Ingrese la marca")) {
            txtMarca.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaKeyPressed

    private void txtMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMarcaMouseEntered
        txtMarca.setEnabled(true);
        txtMarca.requestFocus();
        txtMarca.setCaretPosition(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaMouseEntered

    private void txtMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMarcaMouseExited
        if (txtMarca.getText().equals("")) {
            txtMarca.setText("Ingrese la marca");
            txtMarca.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaMouseExited

    private void txtModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyPressed
        if (txtModelo.getText().equals("Ingrese el modelo")) {
            txtModelo.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloKeyPressed

    private void txtModeloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModeloMouseEntered
        txtModelo.setEnabled(true);
        txtModelo.requestFocus();
        txtModelo.setCaretPosition(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloMouseEntered

    private void txtModeloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModeloMouseExited
        if (txtModelo.getText().equals("")) {
            txtModelo.setText("Ingrese el modelo");
            txtModelo.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloMouseExited

    private void txtImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImgMouseEntered
        txtImg.setEnabled(true);
        txtImg.requestFocus();
        txtImg.setCaretPosition(0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgMouseEntered

    private void txtImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImgMouseExited
        if (txtImg.getText().equals("")) {
            txtImg.setText("XXXX");
            txtImg.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgMouseExited

    private void txtImgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImgKeyPressed
        if (txtImg.getText().equals("XXXX")) {
            txtImg.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgKeyPressed

    private void txtImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAñadir;
    public javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField txtImg;
    public javax.swing.JTextField txtMarca;
    public javax.swing.JTextField txtModelo;
    public javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
